Allow lowercase branch name
thefuntasty/danger pull request #6
Opened 2018-11-13 09:41 UTC by radimvaculik

2018-11-16 11:18 UTC, skywall approved these changes

2018-11-16 14:40 UTC, mkj-is requested changes
I am strongly against enabling both cases.

```
  feature/PROJ-10-oauth
* feature/PROJ-106-event-update-link-sharing
  feature/PROJ-13-gallery-api
  feature/PROJ-17-video-layouts
  feature/PROJ-30-return-error-when-facebook-queue-is-failing
  feature/PROJ-86-dependencies-security-update
  feature/PROJ-88-simplify-token-revocation
  feature/PROJ-89-delete-event-endpoint
```

When it is uppercase, the JIRA-ID can be immediately seen when listing branches.

```
  remotes/origin/feature/PR-109-timeline-info-overlay
  remotes/origin/feature/pr-103-error-view
  remotes/origin/feature/pr-104-cell-stream
  remotes/origin/feature/pr-122-settings-list
```

And when it is both uppercase/lowercase it is not even sorted correctly.

I willing to change this to lowercase letters, but I would only allow one version. Either lowercase or uppercase, not both.

2018-12-03 12:48 UTC, mkj-is commented
Closing this until I get some answers.

2018-12-03 12:48 UTC, closed without merging

2018-12-03 12:55 UTC, radimvaculik commented
:'(